---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Переход между страницами должен произойти без перезагрузки
  - На странице товара и в каталоге должно отобразиться название 
  - На странице товара и в каталоге должнен отобразиться рейтинг
  - На странице товара и в каталоге должна отобразиться цена со скидкой и без нее
  - Пользователь должен иметь возможность продолжать выбирать товары в каталоге после добавления товара в корзину
  - Пользователь должен иметь возможность удалить товар из корзины
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Корзина должна хранится в сессии браузера
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - При добавления товара в корзину должно появляться модальное окно для выбора параметров (цвет, количество товара)
  - Пользователь должен иметь возможность увеличить изображение
  - Пользователь должен иметь возможность выбрать галочками определенные позиции из корзины для заказа
  - Пользователь не может редактировать описание товара
  - Пользователь не может удалить товар со страницы магазина
  - Пользователь не может редактировать цену товара
  - Пользователь не может редактировать фильтр
  - Пользователь не может добавлять товары на страницу магазина
  - Пользователь не может редактировать фотографии в карточке товара
  

  
