---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность создать профиль
  - На сайте должна быть кнопка входа и регистрации
  - При добавления товара в корзину должно появляться модальное окно для выбора параметров (цвет, количество товара)
  - Пользователь должен иметь возможность увеличить изображение
  - Пользователь должен иметь возможность подтвердить заказ перед окончательным оформлением
  - Пользователь должен иметь возможность выбрать галочками определенные позиции из корзины для заказа
  - Должна быть кнопка выбора конкретной страницы с нумерованием
  - Пользователь должен иметь возможность отметить товар как избранный
  - Пользователь должен иметь возможность открыть список с избранными товарами
  - Пользователь должен иметь возможность прсматривать информацию по оформленным заказам
  - Пользователь должен иметь возможность указать адрес доставки
  - При удаления товара из корзины должно появляться модальное окно для подтверждения действия
  - При очистки корзины должно появляться модальное окно для подтверждения действия
  - В форме фильтра должна быть кнопка сброса выбранных параметрах.
  - Пользователь должен иметь возможность выбрать галочками определенные позиции из корзины и удалить одной кнопкой

  
